### ISSUE TITLE
Cannot seem to get this to work

### ISSUE THREAD

**Issue by NetOpWibby** [coderaiser/node-mollify#2]
Hi there,

I am interested in minifying my template `.html` files, but my code doesn't seem to be working. Here is my code:

```
const
  bodyParser = require("body-parser"),
  cookieParser = require("cookie-parser"),
  express = require("express"),
  favicon = require("serve-favicon"),
  hbs = require("hbs"),
  logger = require("morgan"),
  mollify = require("mollify"),
  path = require("path"),
  routes = require("./routes/index");

const app = express()
  .use(mollify({
    dir: path.join(__dirname, "views/pages")
  }))

  .set("view engine", "html")
  .engine("html", hbs.__express)
  .set("views", path.join(__dirname, "views"))
  .set("layouts", path.join(__dirname, "views/layouts"))

  .use(favicon(path.join(__dirname, "public/favicon.ico")))

  .use(logger("dev"))
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: false }))
  .use(cookieParser())
  .use(express.static(path.join(__dirname, "public")))

  .use("/", routes);
```

Everything _looks_ correct, but nothing is minified.

**Comment by coderaiser** [comment]
Hi,

Maybe this is because you serve content from  `path.join(__dirname, "public")` and set `mollify` directory to `path.join(__dirname, "views/pages")`.

Do you have some request from the browser to directory `views/pages`?
`mollify` serves (and cashes) real request only. Anyway minify before serving it is a good idea.

Try example from `readme`, is it work for you?

**Comment by coderaiser** [comment]
Closed due to long time of inactivity.

**Comment by NetOpWibby** [comment]
My apologies for the late reply, I was busy.

I've changed the `mollify` directory to `public` and I nothing's changed.

EDIT: I've even replicated the README's example and I get the same result. The `express-minify-html` package works for me though, so I'm good.

**Comment by coderaiser** [comment]
This is becouse you are using `render`. Actually `express-minify-html` better fits your needs becouse it: `enchances the regular 'render`.

**Comment by NetOpWibby** [comment]
The built-in `render`? How do you setup routes with `mollify` then?

**Comment by coderaiser** [comment]
`Mollify` proxies original request to file system, minifies (once) and cashes result on the way. And then just sends minified content directly from the cache.
