### ISSUE TITLE
[Suggestion] Repo name improvement 

### ISSUE THREAD

**Issue by JakeRowsell89** [coderaiser/node-mollify#5]
As this is middleware for minify, I feel a more sensible name would be "midlify" or even "middlify" to avoid confusion with being something related to the MIDI format. Mollify in popular lingo sounds like it is turning something into Molly/MDMA.

**Comment by coderaiser** [comment]
That's an interesting idea, but the module is already published in `npm` with this name. I see no reason to publish it with a new name, so `npm` will have two same modules with different names :).
